In [35]:
import numpy as np
import pandas as pd

In [36]:
train_ds = pd.read_csv("train.csv")
train_ds

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [37]:
train_ds = train_ds[["Survived", "Pclass", "Name", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]]
train_ds

Survived  Pclass                                               Name  \
0           0       3                            Braund, Mr. Owen Harris   
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2           1       3                             Heikkinen, Miss. Laina   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4           0       3                           Allen, Mr. William Henry   
..        ...     ...                                                ...   
886         0       2                              Montvila, Rev. Juozas   
887         1       1                       Graham, Miss. Margaret Edith   
888         0       3           Johnston, Miss. Catherine Helen "Carrie"   
889         1       1                              Behr, Mr. Karl Howell   
890         0       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch     Fare Embarked  
0      male  22.0      1      0   7.2500        S  
1    female  38.0      1      0  71.2833        C  
2    female  26.0      0      0   7.9250        S  
3    female  35.0      1      0  53.1000        S  
4      male  35.0      0      0   8.0500        S  
..      ...   ...    ...    ...      ...      ...  
886    male  27.0      0      0  13.0000        S  
887  female  19.0      0      0  30.0000        S  
888  female   NaN      1      2  23.4500        S  
889    male  26.0      0      0  30.0000        C  
890    male  32.0      0      0   7.7500        Q  

[891 rows x 9 columns]

In [38]:
train_ds = train_ds.dropna()
train_ds

Survived  Pclass                                               Name  \
0           0       3                            Braund, Mr. Owen Harris   
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2           1       3                             Heikkinen, Miss. Laina   
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4           0       3                           Allen, Mr. William Henry   
..        ...     ...                                                ...   
885         0       3               Rice, Mrs. William (Margaret Norton)   
886         0       2                              Montvila, Rev. Juozas   
887         1       1                       Graham, Miss. Margaret Edith   
889         1       1                              Behr, Mr. Karl Howell   
890         0       3                                Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch     Fare Embarked  
0      male  22.0      1      0   7.2500        S  
1    female  38.0      1      0  71.2833        C  
2    female  26.0      0      0   7.9250        S  
3    female  35.0      1      0  53.1000        S  
4      male  35.0      0      0   8.0500        S  
..      ...   ...    ...    ...      ...      ...  
885  female  39.0      0      5  29.1250        Q  
886    male  27.0      0      0  13.0000        S  
887  female  19.0      0      0  30.0000        S  
889    male  26.0      0      0  30.0000        C  
890    male  32.0      0      0   7.7500        Q  

[712 rows x 9 columns]

In [39]:
train_ds.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  712.000000  712.000000  712.000000  712.000000  712.000000  712.000000
mean     0.404494    2.240169   29.642093    0.514045    0.432584   34.567251
std      0.491139    0.836854   14.492933    0.930692    0.854181   52.938648
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    1.000000   20.000000    0.000000    0.000000    8.050000
50%      0.000000    2.000000   28.000000    0.000000    0.000000   15.645850
75%      1.000000    3.000000   38.000000    1.000000    1.000000   33.000000
max      1.000000    3.000000   80.000000    5.000000    6.000000  512.329200

In [40]:
from tensorflow.keras.utils import to_categorical
Pclass = train_ds["Pclass"].to_numpy()
as_categorical_pclass = to_categorical(Pclass - 1, num_classes = 3)
as_categorical_pclass

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [41]:
def sex_str_to_bin(s):
    if s=="male":
        return 1
    else:
        return 0

sex = train_ds["Sex"]
as_bin_sex = sex.apply(sex_str_to_bin)
as_bin_sex

0      1
1      0
2      0
3      0
4      1
      ..
885    0
886    1
887    0
889    1
890    1
Name: Sex, Length: 712, dtype: int64

In [68]:
age_np = train_ds["Age"].to_numpy()
age_np = (train_ds["Age"] - train_ds["Age"].mean()) / train_ds["Age"].std()
age_np[:10]

0    -0.527298
1     0.576688
2    -0.251301
3     0.369691
4     0.369691
6     1.680675
7    -1.907281
8    -0.182302
9    -1.079291
10   -1.769283
Name: Age, dtype: float64

In [69]:
sibsp = train_ds["SibSp"]
sibsp_np = sibsp.to_numpy()
sibsp_np = (train_ds["SibSp"] - train_ds["SibSp"].mean()) / train_ds["SibSp"].std()
sibsp_np[:10]

0     0.522144
1     0.522144
2    -0.552325
3     0.522144
4    -0.552325
6    -0.552325
7     2.671082
8    -0.552325
9     0.522144
10    0.522144
Name: SibSp, dtype: float64

In [70]:
parch = train_ds["Parch"]
parch_np = parch.to_numpy()
parch_np = (train_ds["Parch"] - train_ds["Parch"].mean()) / train_ds["Parch"].std()
parch_np[:10]

0    -0.506431
1    -0.506431
2    -0.506431
3    -0.506431
4    -0.506431
6    -0.506431
7     0.664280
8     1.834992
9    -0.506431
10    0.664280
Name: Parch, dtype: float64

In [71]:
fare = train_ds["Fare"]
fare_np = fare.to_numpy()
fare_np = (train_ds["Fare"] - train_ds["Fare"].mean()) / train_ds["Fare"].std()
fare_np[:10]

0    -0.516017
1     0.693558
2    -0.503267
3     0.350080
4    -0.500905
6     0.326704
7    -0.254866
8    -0.442662
9    -0.084937
10   -0.337509
Name: Fare, dtype: float64

In [72]:
from sklearn.linear_model import LogisticRegression

In [74]:
X_train = np.concatenate((as_categorical_pclass,
                as_bin_sex.values.reshape(-1,1),
                age_np.values.reshape(-1,1),
                sibsp_np.values.reshape(-1,1),
                parch_np.values.reshape(-1,1),
                fare_np.values.reshape(-1,1)), axis=1)
X_train

array([[ 0.        ,  0.        ,  1.        , ...,  0.52214373,
        -0.50643136, -0.51601717],
       [ 1.        ,  0.        ,  0.        , ...,  0.52214373,
        -0.50643136,  0.69355848],
       [ 0.        ,  0.        ,  1.        , ..., -0.55232545,
        -0.50643136, -0.50326656],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.55232545,
        -0.50643136, -0.08627442],
       [ 1.        ,  0.        ,  0.        , ..., -0.55232545,
        -0.50643136, -0.08627442],
       [ 0.        ,  0.        ,  1.        , ..., -0.55232545,
        -0.50643136, -0.50657227]])

In [75]:
Y_train = train_ds["Survived"].to_numpy()
Y_train[:10]

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1], dtype=int64)

In [78]:
model = LogisticRegression(random_state = 0).fit(X_train, Y_train)
model.score(X_train, Y_train)

0.800561797752809

In [144]:
test_ds = pd.read_csv("test.csv")
test_ds

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [145]:
test_ds = test_ds[['PassengerId', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']]
test_ds

PassengerId  Pclass     Sex   Age  SibSp  Parch      Fare
0            892       3    male  34.5      0      0    7.8292
1            893       3  female  47.0      1      0    7.0000
2            894       2    male  62.0      0      0    9.6875
3            895       3    male  27.0      0      0    8.6625
4            896       3  female  22.0      1      1   12.2875
..           ...     ...     ...   ...    ...    ...       ...
413         1305       3    male   NaN      0      0    8.0500
414         1306       1  female  39.0      0      0  108.9000
415         1307       3    male  38.5      0      0    7.2500
416         1308       3    male   NaN      0      0    8.0500
417         1309       3    male   NaN      1      1   22.3583

[418 rows x 7 columns]

In [146]:
test_ds = test_ds.fillna(test_ds['Age'].mean())
len(test_ds)

418

In [147]:
pclass = test_ds['Pclass'].to_numpy()
as_categorical_pclass = to_categorical(pclass - 1, num_classes=3)
as_categorical_pclass[:10]

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [148]:
sex = test_ds['Sex']
as_binary_sex = sex.apply(sex_str_to_bin).to_numpy()
as_binary_sex[:10]

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 1], dtype=int64)

In [149]:
age_np = test_ds['Age'].to_numpy()
age_np = (age_np - train_ds['Age'].mean()) / train_ds['Age'].std()
age_np[:10]

array([ 0.33519146,  1.19768079,  2.23266799, -0.18230214, -0.52729787,
       -1.07929105,  0.0246953 , -0.25130129, -0.80329446, -0.59629702])

In [150]:
sibsp = test_ds['SibSp']
sibsp_np = sibsp.to_numpy()
sibsp_np = (sibsp_np - train_ds['SibSp'].mean()) / train_ds['SibSp'].std()
sibsp_np[:10]

array([-0.55232545,  0.52214373, -0.55232545, -0.55232545,  0.52214373,
       -0.55232545, -0.55232545,  0.52214373, -0.55232545,  1.5966129 ])

In [151]:
parch = test_ds['Parch']
parch = parch.to_numpy()
parch = (parch - train_ds['Parch'].mean()) / train_ds['Parch'].std()
parch[:10]

array([-0.50643136, -0.50643136, -0.50643136, -0.50643136,  0.66428009,
       -0.50643136, -0.50643136,  0.66428009, -0.50643136, -0.50643136])

In [152]:
fare = test_ds['Fare'].to_numpy()
fare = (fare - train_ds['Fare'].mean()) / train_ds['Fare'].std()
fare[:10]

array([-0.5050762 , -0.52073962, -0.4699733 , -0.48933534, -0.42085985,
       -0.47870983, -0.50885416, -0.10516422, -0.51641008, -0.1967797 ])

In [153]:
test_X = np.concatenate((as_categorical_pclass, 
                as_binary_sex.reshape(-1, 1),
                age_np.reshape(-1, 1),
                sibsp_np.reshape(-1,1),
                parch.reshape(-1,1),
                fare.reshape(-1,1)), axis=1)
test_X

array([[ 0.        ,  0.        ,  1.        , ..., -0.55232545,
        -0.50643136, -0.5050762 ],
       [ 0.        ,  0.        ,  1.        , ...,  0.52214373,
        -0.50643136, -0.52073962],
       [ 0.        ,  1.        ,  0.        , ..., -0.55232545,
        -0.50643136, -0.4699733 ],
       ...,
       [ 0.        ,  0.        ,  1.        , ..., -0.55232545,
        -0.50643136, -0.51601717],
       [ 0.        ,  0.        ,  1.        , ..., -0.55232545,
        -0.50643136, -0.50090534],
       [ 0.        ,  0.        ,  1.        , ...,  0.52214373,
         0.66428009, -0.23062454]])

In [154]:
predictions = model.predict(test_X)
passenger_ids = test_ds['PassengerId'].to_numpy()
sub_df = pd.DataFrame({'PassengerId':passenger_ids, 'Survived':predictions})

In [155]:
sub_df.to_csv('submission.csv')

In [156]:
submission_df = pd.read_csv('gender_submission.csv')
submission_df

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]